/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reservationdesblocsop.frame;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author jawaher
 */
public class login extends javax.swing.JFrame {
   int xMouse;
   int yMouse; 
   Connection conn=null;
   ResultSet   rs = null;
   PreparedStatement ps =null;
   
   
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setSize(1045,625);
        setLocation(250,100);
        conn =connexionBD.conexion();
        loginbtn.setOpaque(false);
        loginbtn.setContentAreaFilled(false);
        loginbtn.setBorderPainted(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbtn = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        resize = new javax.swing.JLabel();
        des = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        movejFrame = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbtnMouseReleased(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 400, 350, 60));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, 20));

        resize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resizeMouseClicked(evt);
            }
        });
        getContentPane().add(resize, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 20, 20));

        des.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        des.setForeground(new java.awt.Color(0, 153, 153));
        des.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        des.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                desMouseMoved(evt);
            }
        });
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 400, 30));

        jPasswordField1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseMoved(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseExited(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 280, 40));

        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField1MouseMoved(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 280, 40));

        movejFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movejFrameMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                movejFrameMouseMoved(evt);
            }
        });
        movejFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movejFrameMousePressed(evt);
            }
        });
        getContentPane().add(movejFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 980, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reservationdesblocop/images/log.png"))); // NOI18N
        back.setRequestFocusEnabled(false);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -350, 2230, 1320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void resizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizeMouseClicked
       this.setState(login.ICONIFIED);
    }//GEN-LAST:event_resizeMouseClicked

    private void movejFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movejFrameMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
        
        
    }//GEN-LAST:event_movejFrameMouseDragged

    private void movejFrameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movejFrameMouseMoved
       
    }//GEN-LAST:event_movejFrameMouseMoved

    private void movejFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movejFrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_movejFrameMousePressed

    private void desMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_desMouseMoved

    private void jTextField1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseMoved
       des.setText("veuillez entrer votre login");
    }//GEN-LAST:event_jTextField1MouseMoved

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        des.setText("");
    }//GEN-LAST:event_jTextField1MouseExited

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       des.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jPasswordField1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseMoved
       des.setText("veuillez entrer votre mot de passe ");
    }//GEN-LAST:event_jPasswordField1MouseMoved

    private void jPasswordField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseExited
        des.setText("");
    }//GEN-LAST:event_jPasswordField1MouseExited

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
          des.setText("");  
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
 String requete ="select * from login_table where login = ? and password = ?";
   try{
       ps= conn.prepareStatement(requete);
       ps.setString(1,jTextField1.getText());
       ps.setString(2,jPasswordField1.getText());
       rs = ps.executeQuery();
       if( rs.next()){
           System.out.println("correct login");
           dispose();
           new specialités().setVisible(true);}
   }
       catch(Exception e){
               System.out.println("--> Exception : " + e);
               }
   
   des.setText("Erreur");
   System.out.println("login failed");
    }//GEN-LAST:event_loginbtnActionPerformed

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
          ImageIcon img = new ImageIcon(getClass().getResource("boutton_hover_login.png"));
      loginbtn.setIcon(img);
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
             ImageIcon img = new ImageIcon(getClass().getResource("login_btn.png"));
      loginbtn.setIcon(img);
    }//GEN-LAST:event_loginbtnMouseExited

    private void loginbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMousePressed
       ImageIcon img = new ImageIcon(getClass().getResource(""));
       ImageIcon img2 = new ImageIcon(getClass().getResource("boutton_hover_login.png")); 
    loginbtn.setIcon(img);
       loginbtn.setIcon(img2);      
    }//GEN-LAST:event_loginbtnMousePressed

    private void loginbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseReleased
        ImageIcon img = new ImageIcon(getClass().getResource("login_btn.png"));
      loginbtn.setIcon(img);
    }//GEN-LAST:event_loginbtnMouseReleased

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JLabel des;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel movejFrame;
    private javax.swing.JLabel resize;
    // End of variables declaration//GEN-END:variables
}
