/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reservationdesblocsop.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chayma
 */
public class ophtalmologie extends javax.swing.JInternalFrame {

    /**
     * Creates new form ophtalmologie
     */
    public ophtalmologie() {
        initComponents();
        showbloc();
    }
    public ArrayList<seulebloc> ophtaList(){
        ArrayList<seulebloc> ophtabloc = new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/reservationf","root",""); 
            String query =" select * from blocophta";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query);
            seulebloc oph;
            while(rs.next()){
            oph =new seulebloc(rs.getString("N° bloc"));
            ophtabloc.add(oph);
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog( null,e); 
        }
        return ophtabloc;
          
    
    }
    public void showbloc(){
    ArrayList<seulebloc> oph = ophtaList();
    DefaultTableModel model = (DefaultTableModel)table.getModel();
    Object[] row = new Object[1];
    for(int i=0;i<oph.size();i++){
    row[0]=oph.get(i).getNbloc();
   
       model.addRow(row);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("ophtalmologie");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOC"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reservationdesblocop/images/jj.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
         DefaultTableModel model = (DefaultTableModel)table.getModel();
       int selectedrow = table.getSelectedRow();
       String selected =model.getValueAt(selectedrow,0).toString();
       String m ="bloc 3";
       String n="bloc 4";
       if(selected.equals(m)){
       bloc3 bloc = new bloc3();
       bloc.setVisible(true);}
       else{
       bloc4 bloc = new bloc4();
       bloc.setVisible(true);
       }
     
    }//GEN-LAST:event_tableMouseClicked

public static void main(String[] args) { 
// Does whatever you want your program to do 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
