/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reservationdesblocsop.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author chayma
 */
public class ortho extends javax.swing.JInternalFrame {

    /**
     * Creates new form ortho
     */
    public ortho() {
        initComponents();
        showbloc();
    }
   
     public ArrayList<seulebloc> orthoList(){
        ArrayList<seulebloc> orthobloc = new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/reservationf","root",""); 
            String query =" select * from blocortho";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query);
            seulebloc ortho;
            while(rs.next()){
            ortho =new seulebloc(rs.getString("N° bloc"));
            orthobloc.add(ortho);
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog( null,e); 
        }
        return orthobloc;
          
    
    }
    public void showbloc(){
    ArrayList<seulebloc> oph = orthoList();
    DefaultTableModel model = (DefaultTableModel)table.getModel();
    Object[] row = new Object[1];
    for(int i=0;i<oph.size();i++){
    row[0]=oph.get(i).getNbloc();
     ;
       model.addRow(row);
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Orthologie");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2143, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 514, 2143, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOC"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reservationdesblocop/images/jj.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
          DefaultTableModel model = (DefaultTableModel)table.getModel();
       int selectedrow = table.getSelectedRow();
       String selected =model.getValueAt(selectedrow,0).toString();
       String m ="bloc 15";
       String n="bloc 16";
       if(selected.equals(m)){
       bloc15 bloc = new bloc15();
       bloc.setVisible(true);}
       else{
       bloc16 bloc = new bloc16();
       bloc.setVisible(true);
       }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
