/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reservationdesblocsop.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chayma
 */
public class plas extends javax.swing.JInternalFrame {

    /**
     * Creates new form plas
     */
    public plas() throws ClassNotFoundException, SQLException {
        initComponents();
        showbloc();
    }
public ArrayList<seulebloc> plasBloc() throws ClassNotFoundException, SQLException{
        ArrayList<seulebloc> plasbloc = new ArrayList<>();
            try {
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/reservationf","root",""); 
            String query =" select * from blocplas";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query);
            seulebloc stomo;
            while(rs.next())
            {stomo =new seulebloc(rs.getString("N° bloc"));
            plasbloc.add(stomo);
                
            }
            }
            catch(Exception e){
        JOptionPane.showMessageDialog( null,e); 
            }
        return plasbloc;
}
       public void showbloc() throws ClassNotFoundException, SQLException{
    ArrayList<seulebloc> oph = plasBloc();
    DefaultTableModel model = (DefaultTableModel)table.getModel();
    Object[] row = new Object[5];
    for(int i=0;i<oph.size();i++){
    row[0]=oph.get(i).getNbloc();

       model.addRow(row);
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Plastique et Esthétique");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOC"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reservationdesblocop/images/jj.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
             DefaultTableModel model = (DefaultTableModel)table.getModel();
       int selectedrow = table.getSelectedRow();
       String selected =model.getValueAt(selectedrow,0).toString();
       String m ="bloc 13";
       String n="bloc 14";
       if(selected.equals(m)){
       bloc13 bloc = new bloc13();
       bloc.setVisible(true);}
       else{
       bloc14 bloc = new bloc14();
       bloc.setVisible(true);
       }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
