/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reservationdesblocsop.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chayma
 */
public class stomatologie extends javax.swing.JInternalFrame {

    /**
     * Creates new form stomatologie
     */
    public stomatologie() throws ClassNotFoundException, SQLException {
        initComponents();
        showbloc();
    }
      public ArrayList<seulebloc> stomoBloc() throws ClassNotFoundException, SQLException{
        ArrayList<seulebloc> urobloc = new ArrayList<>();
            try {
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/reservationf","root",""); 
            String query =" select * from blocstoma";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query);
            seulebloc stomo;
            while(rs.next())
            {stomo =new seulebloc(rs.getString("N° bloc"));
            urobloc.add(stomo);
                
            }
            }
            catch(Exception e){
        JOptionPane.showMessageDialog( null,e); 
            }
        return urobloc;
}
       public void showbloc() throws ClassNotFoundException, SQLException{
    ArrayList<seulebloc> oph = stomoBloc();
    DefaultTableModel model = (DefaultTableModel)table.getModel();
    Object[] row = new Object[1];
    for(int i=0;i<oph.size();i++){
    row[0]=oph.get(i).getNbloc();
    
       model.addRow(row);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("stomatologie");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOC"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reservationdesblocop/images/jj.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
            DefaultTableModel model = (DefaultTableModel)table.getModel();
       int selectedrow = table.getSelectedRow();
       String selected =model.getValueAt(selectedrow,0).toString();
       String m ="bloc 11";
       String n="bloc 12";
       if(selected.equals(m)){
       bloc11 bloc = new bloc11();
       bloc.setVisible(true);}
       else{
       bloc12 bloc = new bloc12();
       bloc.setVisible(true);
       }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
